spring:
  application:
    name: SpringSecurity

  data:
    mongodb:
      uri: mongodb+srv://bhupalprajapati:Prajapati@cluster0.wajlmyk.mongodb.net/JournalDB?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
      ssl:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: bhupalt001@gmail.com
    password: "omkg cwck ujnx uirc"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  spring-boot:
    run:
      jvmArguments: "-Dhttps.protocols=TLSv1.2"
